# Execute ansible-galaxy init to create the shipit role
ansible-container:
  image: "{{ builder_img_id }}"
  command: ansible-galaxy init -p /roles --force {{ role_name }}
  volumes:
      - {{ roles_path }}:/roles
{{ config }}
