ansible-container:
  image: "{{ builder_img_id }}"
  command: ansible-playbook -i /etc/ansible/inventory/hosts -c docker {{ params.ansible_options }} --list-hosts main.yml
  environment:
    - DOCKER_HOST
    - DOCKER_TLS_VERIFY
    - DOCKER_CERT_PATH=/docker-certs/
    - COMPOSE_HTTP_TIMEOUT=3000
  volumes:
    - {{ which_docker }}:/usr/bin/docker
    - $DOCKER_CERT_PATH:/docker-certs/
    - {{ base_path }}:/ansible-container/
  working_dir: /ansible-container/ansible/
  stdin_open: true
  tty: true
{{ config }}
